Repository NethServer/ns8-core, pull requests merged in 2022-12, with the labels that each got.

#321 Fix module missing permissions
  core/imageroot/usr/local/agent/pypkg/agent/__init__.py
  core/imageroot/usr/local/agent/pypkg/cluster/grants.py
  core/imageroot/var/lib/nethserver/cluster/actions/add-module/50update
  core/imageroot/var/lib/nethserver/cluster/actions/remove-module/50update
  docs/core/agents.md
  docs/core/database.md
Labels: bug

#322 Allow addition of pip packages
  core/imageroot/var/lib/nethserver/node/install-core.sh
Labels: enhancement, testing

#319 Agent function http_route_in_use and tcp_port_in_use
  core/imageroot/usr/local/agent/pypkg/agent/__init__.py
Labels: enhancement, testing

#323 Override replace flag for restore-module
  core/imageroot/var/lib/nethserver/cluster/actions/restore-module/50restore_module
Labels: bug

#324 Drop agent dump-env command
  core/agent/README.md
  core/agent/agent.go
  core/agent/envstate.go
  core/agent/hevent.go
  core/agent/htask.go
  core/agent/test/actions/dump-environment/10setenv
  core/agent/test/actions/dump-environment/20dumpenv
  core/agent/test/actions/dump-environment/30failure
  core/agent/test/suite/20__environment.robot
  core/agent/test/suite/60__shutdown.robot
  core/imageroot/usr/local/agent/pypkg/agent/__init__.py
  docs/modules/agent.md
Labels: enhancement, testing

#327 Fix clone-module auth error
  core/imageroot/usr/local/agent/actions/transfer-state/50sendstate
Labels: bug, testing

#326 Listen for events on local Redis replica
  core/agent/hevent.go
  core/imageroot/etc/nethserver/agent.env
  core/imageroot/usr/local/agent/pypkg/agent/__init__.py
Labels: testing
